
spring:
  profiles.active: testing

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #Druid连接池
    url: jdbc:mysql://10.122.1.139:3306/supervisory_control?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: test1 #数据库用户名
    password: 123456 #数据库密码
#    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    initialSize: 10 #初始化连接池大小
    minIdle: 10 #初始化最小连接池数量
    maxActive: 100 #初始化最大连接池数量
    maxWait: 6000 #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMills: 6000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 'x' #测试连接

  redis:
    port: 6379
    host: localhost
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    connect-timeout: 5000ms
mybatis:
  mapper-locations: classpath:mapper/*.xml
---
spring:
  profiles: development
server.port: 8081

---
spring:
  profiles: testing
server.port: 8082

---
spring:
  profiles: product
server.port: 8083


